export const DATA = {
  git: {
    label: "Git",
    accent: "#f05033",
    icon: "⎇",
    cats: {
      "Setup & Config": [
        ["git init", "Initialize a new local repository"],
        ["git clone <url>", "Clone a remote repository"],
        ["git config --global user.name 'Name'", "Set global username"],
        ["git config --global user.email 'email'", "Set global email"],
        ["git config --list", "List all config settings"],
      ],
      "Staging & Commits": [
        ["git status", "Show working tree status"],
        ["git add .", "Stage all changes"],
        ["git add <file>", "Stage a specific file"],
        ["git commit -m 'msg'", "Commit with message"],
        ["git commit --amend", "Amend last commit"],
        ["git reset HEAD <file>", "Unstage a file"],
        ["git checkout -- <file>", "Discard file changes"],
      ],
      "Branches": [
        ["git branch", "List all branches"],
        ["git branch <name>", "Create a new branch"],
        ["git checkout <branch>", "Switch to branch"],
        ["git checkout -b <branch>", "Create and switch to branch"],
        ["git merge <branch>", "Merge branch into current"],
        ["git branch -d <branch>", "Delete a branch"],
        ["git branch -D <branch>", "Force delete a branch"],
        ["git rebase <branch>", "Rebase onto branch"],
      ],
      "Remote": [
        ["git remote -v", "List remote connections"],
        ["git remote add origin <url>", "Add a remote"],
        ["git fetch origin", "Fetch from remote"],
        ["git pull origin <branch>", "Pull from remote branch"],
        ["git push origin <branch>", "Push to remote branch"],
        ["git push -u origin <branch>", "Push and set upstream"],
        ["git push --force", "Force push (destructive!)"],
      ],
      "History & Diff": [
        ["git log", "Show commit history"],
        ["git log --oneline --graph", "Compact graph view"],
        ["git diff", "Show unstaged changes"],
        ["git diff --staged", "Show staged changes"],
        ["git show <commit>", "Show a specific commit"],
        ["git blame <file>", "Show who changed each line"],
      ],
      "Undo & Stash": [
        ["git revert <commit>", "Revert a commit safely"],
        ["git reset --hard HEAD~1", "Undo last commit (destructive)"],
        ["git stash", "Stash current changes"],
        ["git stash pop", "Apply and drop latest stash"],
        ["git stash list", "List all stashes"],
        ["git clean -fd", "Remove untracked files"],
      ],
      "Tags": [
        ["git tag", "List tags"],
        ["git tag v1.0.0", "Create a lightweight tag"],
        ["git tag -a v1.0.0 -m 'msg'", "Create annotated tag"],
        ["git push origin --tags", "Push all tags"],
      ],
    },
  },

  linux: {
    label: "Linux",
    accent: "#4caf7d",
    icon: "🐧",
    cats: {
      "Navigation": [
        ["pwd", "Print working directory"],
        ["ls -la", "List all files with details"],
        ["cd <dir>", "Change directory"],
        ["cd ..", "Go up one directory"],
        ["cd ~", "Go to home directory"],
        ["tree", "Display directory tree"],
      ],
      "Files & Directories": [
        ["mkdir -p <dir>", "Create directory (and parents)"],
        ["touch <file>", "Create empty file"],
        ["cp -r <src> <dst>", "Copy file or directory"],
        ["mv <src> <dst>", "Move or rename"],
        ["rm -rf <dir>", "Remove directory recursively"],
        ["ln -s <target> <link>", "Create symbolic link"],
        ["find . -name '*.log'", "Find files by name"],
        ["find . -type f -mtime -7", "Files modified in last 7 days"],
      ],
      "Text & Search": [
        ["cat <file>", "Print file contents"],
        ["less <file>", "View file page by page"],
        ["head -n 20 <file>", "Show first 20 lines"],
        ["tail -f <file>", "Follow file in real-time"],
        ["grep -r 'pattern' .", "Recursive search in files"],
        ["grep -n 'pattern' <file>", "Search with line numbers"],
        ["sed -i 's/old/new/g' <file>", "Find and replace in file"],
        ["awk '{print $1}' <file>", "Print first column"],
        ["wc -l <file>", "Count lines in file"],
        ["sort <file> | uniq -c", "Count unique lines"],
      ],
      "Permissions": [
        ["chmod 755 <file>", "rwxr-xr-x permissions"],
        ["chmod +x <file>", "Make file executable"],
        ["chown user:group <file>", "Change file owner"],
        ["ls -lah", "List with human-readable sizes"],
        ["umask 022", "Set default permissions mask"],
      ],
      "Process Management": [
        ["ps aux", "List all running processes"],
        ["ps aux | grep <name>", "Find process by name"],
        ["kill -9 <PID>", "Force kill process by PID"],
        ["pkill <name>", "Kill process by name"],
        ["top", "Interactive process viewer"],
        ["htop", "Enhanced process viewer"],
        ["nohup <cmd> &", "Run command immune to hangup"],
        ["jobs", "List background jobs"],
        ["fg %1", "Bring job 1 to foreground"],
        ["bg %1", "Resume job 1 in background"],
      ],
      "Networking": [
        ["curl -I <url>", "Fetch HTTP headers"],
        ["curl -O <url>", "Download file"],
        ["wget <url>", "Download file with wget"],
        ["ping <host>", "Ping a host"],
        ["netstat -tlnp", "Show listening ports"],
        ["ss -tlnp", "Modern netstat alternative"],
        ["lsof -i :<port>", "Process using a port"],
        ["ip addr show", "Show IP addresses"],
        ["ssh user@host", "Connect via SSH"],
        ["scp file user@host:/path", "Secure copy to remote"],
        ["rsync -avz src/ dst/", "Sync files remotely"],
      ],
      "Disk & System": [
        ["df -h", "Disk usage of filesystems"],
        ["du -sh <dir>", "Size of a directory"],
        ["free -h", "Memory usage"],
        ["uname -a", "System information"],
        ["uptime", "System uptime and load"],
        ["whoami", "Current user"],
        ["history", "Command history"],
        ["which <cmd>", "Path to a command"],
        ["env", "List environment variables"],
        ["export VAR=value", "Set environment variable"],
        ["crontab -e", "Edit cron jobs"],
      ],
      "Archives": [
        ["tar -czf out.tar.gz <dir>", "Compress to tar.gz"],
        ["tar -xzf file.tar.gz", "Extract tar.gz"],
        ["zip -r out.zip <dir>", "Zip a directory"],
        ["unzip file.zip", "Unzip a file"],
      ],
    },
  },

  mac: {
    label: "macOS",
    accent: "#c8a8ff",
    icon: "🍎",
    cats: {
      "Finder & System": [
        ["open .", "Open current dir in Finder"],
        ["open -a 'App Name'", "Open an application"],
        ["open <file>", "Open file with default app"],
        ["mdfind 'query'", "Spotlight search from terminal"],
        ["pbcopy < <file>", "Copy file to clipboard"],
        ["pbpaste > <file>", "Paste clipboard to file"],
        ["say 'hello'", "Text-to-speech"],
        ["scutil --get HostName", "Get hostname"],
      ],
      "Homebrew": [
        ["brew install <pkg>", "Install a formula"],
        ["brew uninstall <pkg>", "Uninstall a formula"],
        ["brew update", "Update Homebrew"],
        ["brew upgrade", "Upgrade all packages"],
        ["brew list", "List installed packages"],
        ["brew search <name>", "Search for a package"],
        ["brew doctor", "Check for issues"],
        ["brew cleanup", "Remove old versions"],
        ["brew services start <svc>", "Start a service"],
        ["brew services stop <svc>", "Stop a service"],
        ["brew services list", "List all services"],
      ],
      "System Info": [
        ["sw_vers", "macOS version info"],
        ["system_profiler SPHardwareDataType", "Hardware details"],
        ["diskutil list", "List disks"],
        ["sysctl -n hw.ncpu", "Number of CPUs"],
        ["sysctl -n hw.memsize", "Total RAM in bytes"],
        ["sudo dscacheutil -flushcache", "Flush DNS cache"],
        ["networksetup -listallnetworkservices", "List network services"],
      ],
      "Productivity": [
        ["caffeinate", "Prevent sleep"],
        ["caffeinate -t 3600", "Prevent sleep for 1 hour"],
        ["screencapture -x ~/ss.png", "Screenshot silently"],
        ["lsof -i TCP:3000", "Process on port 3000"],
        ["sudo lsof -i :80", "Process on port 80"],
        ["killall Dock", "Restart the Dock"],
        ["killall Finder", "Restart Finder"],
      ],
    },
  },

  keyboard: {
    label: "Shortcuts",
    accent: "#f7c948",
    icon: "⌨",
    isShortcut: true,
    cats: {
      "VS Code": [
        ["⌘P / Ctrl+P", "Quick open file"],
        ["⌘⇧P / Ctrl+Shift+P", "Command palette"],
        ["⌘B / Ctrl+B", "Toggle sidebar"],
        ["⌘J / Ctrl+J", "Toggle terminal"],
        ["⌘D / Ctrl+D", "Select next occurrence"],
        ["⌘⇧L / Ctrl+Shift+L", "Select all occurrences"],
        ["⌥↑/↓ / Alt+↑/↓", "Move line up/down"],
        ["⌘⇧K / Ctrl+Shift+K", "Delete line"],
        ["⌘/ / Ctrl+/", "Toggle line comment"],
        ["F12", "Go to definition"],
        ["Alt+F12", "Peek definition"],
        ["F2", "Rename symbol"],
        ["Ctrl+`", "Open integrated terminal"],
      ],
      "Terminal": [
        ["Ctrl+C", "Interrupt / cancel process"],
        ["Ctrl+Z", "Suspend process to background"],
        ["Ctrl+D", "Exit / EOF"],
        ["Ctrl+L", "Clear screen"],
        ["Ctrl+R", "Reverse history search"],
        ["Ctrl+A", "Move to beginning of line"],
        ["Ctrl+E", "Move to end of line"],
        ["Ctrl+U", "Delete to beginning of line"],
        ["Ctrl+K", "Delete to end of line"],
        ["Ctrl+W", "Delete word backward"],
        ["Tab", "Autocomplete"],
        ["↑ / ↓", "Navigate command history"],
      ],
      "Chrome / Browser": [
        ["⌘T / Ctrl+T", "New tab"],
        ["⌘W / Ctrl+W", "Close tab"],
        ["⌘⇧T / Ctrl+Shift+T", "Reopen closed tab"],
        ["⌘L / Ctrl+L", "Focus address bar"],
        ["⌘R / Ctrl+R", "Reload page"],
        ["⌘⇧R / Ctrl+Shift+R", "Hard reload (no cache)"],
        ["⌘⌥I / Ctrl+Shift+I", "Open DevTools"],
        ["⌘⌥J / Ctrl+Shift+J", "Open Console"],
        ["⌘F / Ctrl+F", "Find on page"],
        ["⌘⇧C / Ctrl+Shift+C", "Inspect element"],
        ["F12", "Toggle DevTools"],
      ],
      "macOS System": [
        ["⌘Space", "Spotlight search"],
        ["⌘Tab", "Switch apps"],
        ["⌘`", "Switch windows in app"],
        ["⌘Q", "Quit app"],
        ["⌘H", "Hide app"],
        ["⌘M", "Minimize window"],
        ["⌘,", "Open preferences"],
        ["⌘⇧3", "Screenshot full screen"],
        ["⌘⇧4", "Screenshot selection"],
        ["⌘⇧5", "Screenshot options"],
        ["⌃⌘Space", "Emoji picker"],
        ["⌘⌥Esc", "Force quit"],
      ],
    },
  },

  mysql: {
    label: "MySQL",
    accent: "#00aeff",
    icon: "🐬",
    cats: {
      "Connection & DB": [
        ["mysql -u root -p", "Connect as root"],
        ["mysql -u user -h host -p db", "Connect to remote DB"],
        ["SHOW DATABASES;", "List all databases"],
        ["USE dbname;", "Switch to database"],
        ["SELECT DATABASE();", "Current database"],
        ["SHOW TABLES;", "List all tables"],
        ["DESCRIBE tablename;", "Show table structure"],
        ["SHOW CREATE TABLE t;", "Show CREATE statement"],
        ["SHOW PROCESSLIST;", "Show active queries"],
      ],
      "DDL — Structure": [
        ["CREATE DATABASE dbname;", "Create a database"],
        ["DROP DATABASE dbname;", "Drop a database"],
        ["CREATE TABLE t (id INT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(100));", "Create a table"],
        ["ALTER TABLE t ADD col VARCHAR(50);", "Add a column"],
        ["ALTER TABLE t DROP COLUMN col;", "Drop a column"],
        ["ALTER TABLE t MODIFY col INT NOT NULL;", "Modify column type"],
        ["DROP TABLE tablename;", "Drop a table"],
        ["TRUNCATE TABLE t;", "Delete all rows fast"],
        ["CREATE INDEX idx ON t(col);", "Create an index"],
        ["SHOW INDEXES FROM t;", "List indexes"],
      ],
      "DML — Data": [
        ["INSERT INTO t (a,b) VALUES (1,'x');", "Insert a row"],
        ["INSERT INTO t (a,b) VALUES (1,'x'),(2,'y');", "Insert multiple rows"],
        ["UPDATE t SET col=val WHERE id=1;", "Update a row"],
        ["DELETE FROM t WHERE id=1;", "Delete a row"],
        ["SELECT * FROM t;", "Select all rows"],
        ["SELECT col FROM t WHERE cond LIMIT 10;", "Select with filter"],
        ["SELECT * FROM t ORDER BY col DESC;", "Select with ordering"],
        ["SELECT COUNT(*) FROM t;", "Count rows"],
        ["SELECT DISTINCT col FROM t;", "Select unique values"],
        ["SELECT a.*, b.name FROM a JOIN b ON a.bid=b.id;", "Inner join"],
        ["SELECT * FROM a LEFT JOIN b ON a.id=b.aid;", "Left join"],
        ["SELECT col, COUNT(*) FROM t GROUP BY col HAVING COUNT(*) > 1;", "Group by with having"],
      ],
      "Users & Permissions": [
        ["CREATE USER 'u'@'%' IDENTIFIED BY 'pass';", "Create a user"],
        ["GRANT ALL ON db.* TO 'u'@'%';", "Grant all privileges"],
        ["GRANT SELECT, INSERT ON db.t TO 'u'@'%';", "Grant specific privileges"],
        ["REVOKE ALL ON db.* FROM 'u'@'%';", "Revoke privileges"],
        ["FLUSH PRIVILEGES;", "Reload privilege tables"],
        ["SHOW GRANTS FOR 'u'@'%';", "Show user grants"],
        ["DROP USER 'u'@'%';", "Drop a user"],
        ["ALTER USER 'u'@'%' IDENTIFIED BY 'newpass';", "Change password"],
      ],
      "Admin & Backup": [
        ["mysqldump -u root -p dbname > backup.sql", "Export database"],
        ["mysql -u root -p dbname < backup.sql", "Import SQL file"],
        ["EXPLAIN SELECT ...;", "Analyze query plan"],
        ["SHOW VARIABLES LIKE 'datadir';", "Show data directory"],
        ["SHOW STATUS LIKE 'Threads_connected';", "Active connections"],
        ["SET GLOBAL slow_query_log=ON;", "Enable slow query log"],
      ],
    },
  },

  mongo: {
    label: "MongoDB",
    accent: "#6fcc4a",
    icon: "🍃",
    cats: {
      "Connection & DB": [
        ["mongosh", "Connect to local MongoDB"],
        ["mongosh 'mongodb://host:27017/db'", "Connect to remote"],
        ["show dbs", "List all databases"],
        ["use dbname", "Switch/create database"],
        ["db.getName()", "Current database"],
        ["show collections", "List all collections"],
        ["db.stats()", "Database stats"],
        ["db.dropDatabase()", "Drop current database"],
      ],
      "CRUD — Read": [
        ["db.col.find()", "Find all documents"],
        ["db.col.find().pretty()", "Find all (formatted)"],
        ["db.col.findOne({key:'val'})", "Find one document"],
        ["db.col.find({age:{$gt:25}})", "Find where age > 25"],
        ["db.col.find({}, {name:1, _id:0})", "Projection (select fields)"],
        ["db.col.find().limit(10)", "Limit results"],
        ["db.col.find().skip(20).limit(10)", "Paginate results"],
        ["db.col.find().sort({name:1})", "Sort ascending"],
        ["db.col.countDocuments({})", "Count documents"],
        ["db.col.distinct('field')", "Distinct values"],
      ],
      "CRUD — Write": [
        ["db.col.insertOne({key:'val'})", "Insert one document"],
        ["db.col.insertMany([{},{}])", "Insert many documents"],
        ["db.col.updateOne({_id:id},{$set:{key:'val'}})", "Update one document"],
        ["db.col.updateMany({active:true},{$set:{v:2}})", "Update many documents"],
        ["db.col.replaceOne({_id:id},{newDoc})", "Replace a document"],
        ["db.col.deleteOne({_id:id})", "Delete one document"],
        ["db.col.deleteMany({active:false})", "Delete many documents"],
      ],
      "Query Operators": [
        ["$eq, $ne, $gt, $lt, $gte, $lte", "Comparison operators"],
        ["$in: [val1, val2]", "Match any in array"],
        ["$nin: [val1, val2]", "Match none in array"],
        ["$and: [{}, {}]", "Logical AND"],
        ["$or: [{}, {}]", "Logical OR"],
        ["$exists: true/false", "Field exists check"],
        ["$regex: /pattern/i", "Regex match"],
        ["$text: {$search: 'word'}", "Full-text search"],
        ["$elemMatch: {score:{$gt:80}}", "Match array element"],
      ],
      "Aggregation": [
        ["db.col.aggregate([{$match:{}},{$group:{_id:'$field',count:{$sum:1}}}])", "Group and count"],
        ["$project: {name:1, total:{$sum:'$items'}}", "Reshape documents"],
        ["$lookup: {from:'other',localField:'id',foreignField:'_id',as:'joined'}", "Join collections"],
        ["$unwind: '$arrayField'", "Deconstruct array"],
        ["$sort: {score:-1}", "Sort in pipeline"],
        ["$limit: 10", "Limit in pipeline"],
        ["$count: 'total'", "Count in pipeline"],
      ],
      "Indexes & Admin": [
        ["db.col.createIndex({field:1})", "Create ascending index"],
        ["db.col.createIndex({field:1},{unique:true})", "Create unique index"],
        ["db.col.createIndex({a:1,b:-1})", "Compound index"],
        ["db.col.getIndexes()", "List indexes"],
        ["db.col.dropIndex('name')", "Drop an index"],
        ["db.col.explain().find({})", "Explain query plan"],
        ["mongodump --db dbname --out ./backup", "Dump database"],
        ["mongorestore --db dbname ./backup/dbname", "Restore database"],
      ],
    },
  },

  docker: {
    label: "Docker",
    accent: "#29b6f6",
    icon: "🐳",
    cats: {
      "Images": [
        ["docker images", "List local images"],
        ["docker pull <image>", "Pull image from registry"],
        ["docker build -t name:tag .", "Build image from Dockerfile"],
        ["docker rmi <image>", "Remove an image"],
        ["docker image prune", "Remove unused images"],
        ["docker push <image>", "Push image to registry"],
        ["docker tag <src> <dst>", "Tag an image"],
        ["docker history <image>", "Show image layers"],
      ],
      "Containers": [
        ["docker run -it ubuntu bash", "Run interactively"],
        ["docker run -d -p 8080:80 nginx", "Run detached with port"],
        ["docker run --rm ubuntu echo hello", "Run and remove on exit"],
        ["docker run -e ENV=val image", "Run with env variable"],
        ["docker run -v /host:/container image", "Mount a volume"],
        ["docker ps", "List running containers"],
        ["docker ps -a", "List all containers"],
        ["docker stop <id>", "Stop a container"],
        ["docker start <id>", "Start a container"],
        ["docker restart <id>", "Restart a container"],
        ["docker rm <id>", "Remove a container"],
        ["docker exec -it <id> bash", "Shell into running container"],
        ["docker logs -f <id>", "Follow container logs"],
        ["docker inspect <id>", "Detailed container info"],
        ["docker stats", "Live resource usage"],
      ],
      "Docker Compose": [
        ["docker compose up -d", "Start services detached"],
        ["docker compose down", "Stop and remove services"],
        ["docker compose down -v", "Stop and remove with volumes"],
        ["docker compose ps", "List compose services"],
        ["docker compose logs -f", "Follow compose logs"],
        ["docker compose build", "Build all images"],
        ["docker compose exec svc bash", "Shell into service"],
        ["docker compose run --rm svc cmd", "Run one-off command"],
      ],
      "Volumes & Networks": [
        ["docker volume ls", "List volumes"],
        ["docker volume create name", "Create a volume"],
        ["docker volume rm name", "Remove a volume"],
        ["docker volume prune", "Remove unused volumes"],
        ["docker network ls", "List networks"],
        ["docker network create mynet", "Create a network"],
        ["docker network connect mynet <id>", "Connect container to network"],
      ],
      "Cleanup": [
        ["docker system prune", "Remove all unused resources"],
        ["docker system prune -a", "Remove everything unused"],
        ["docker system df", "Show disk usage"],
        ["docker container prune", "Remove stopped containers"],
        ["docker image prune -a", "Remove all unused images"],
      ],
    },
  },

  npm: {
    label: "npm / Node",
    accent: "#cb3837",
    icon: "📦",
    cats: {
      "npm Basics": [
        ["npm init -y", "Init project with defaults"],
        ["npm install", "Install all dependencies"],
        ["npm install <pkg>", "Install a package"],
        ["npm install -D <pkg>", "Install as devDependency"],
        ["npm install -g <pkg>", "Install globally"],
        ["npm uninstall <pkg>", "Remove a package"],
        ["npm update", "Update all packages"],
        ["npm outdated", "Check for outdated packages"],
        ["npm list", "List installed packages"],
        ["npm list -g --depth=0", "List global packages"],
        ["npm run <script>", "Run a script"],
        ["npm start", "Run start script"],
        ["npm test", "Run test script"],
        ["npm audit", "Security audit"],
        ["npm audit fix", "Fix audit issues"],
        ["npm publish", "Publish package to registry"],
        ["npm cache clean --force", "Clear npm cache"],
      ],
      "npx": [
        ["npx create-react-app myapp", "Bootstrap React app"],
        ["npx create-next-app@latest", "Bootstrap Next.js app"],
        ["npx <pkg>", "Run a package without installing"],
        ["npx -y <pkg>", "Run, auto-confirm install"],
      ],
      "Node.js": [
        ["node --version", "Check Node version"],
        ["node <file.js>", "Run a JS file"],
        ["node -e 'code'", "Run inline JS code"],
        ["node --inspect <file>", "Start debugger"],
        ["process.env.NODE_ENV", "Read environment variable"],
        ["process.exit(0)", "Exit process cleanly"],
      ],
      "nvm": [
        ["nvm install 20", "Install Node 20"],
        ["nvm use 20", "Use Node 20"],
        ["nvm ls", "List installed versions"],
        ["nvm ls-remote", "List all available versions"],
        ["nvm alias default 20", "Set default version"],
        ["nvm current", "Show current version"],
      ],
    },
  },

  vim: {
    label: "Vim",
    accent: "#ff7a5a",
    icon: "✦",
    cats: {
      "Modes": [
        ["i", "Enter Insert mode"],
        ["Esc / Ctrl+[", "Back to Normal mode"],
        ["v", "Enter Visual mode"],
        ["V", "Enter Visual Line mode"],
        ["Ctrl+V", "Enter Visual Block mode"],
        [":", "Enter Command mode"],
        ["R", "Enter Replace mode"],
      ],
      "Navigation": [
        ["h j k l", "Left, Down, Up, Right"],
        ["w / b", "Next / previous word"],
        ["e", "End of word"],
        ["0 / $", "Start / end of line"],
        ["gg / G", "Top / bottom of file"],
        [":<n>", "Go to line n"],
        ["Ctrl+F / Ctrl+B", "Page down / up"],
        ["%", "Jump to matching bracket"],
        ["*", "Search current word"],
      ],
      "Editing": [
        ["x", "Delete character"],
        ["dd", "Delete line"],
        ["yy", "Yank (copy) line"],
        ["p / P", "Paste after / before"],
        ["u / Ctrl+R", "Undo / Redo"],
        ["ciw", "Change inner word"],
        ["di(", "Delete inside parentheses"],
        [">>", "Indent line right"],
        ["<<", "Indent line left"],
        ["J", "Join line below"],
        [".", "Repeat last action"],
        ["~", "Toggle case"],
      ],
      "Search & Replace": [
        ["/<pattern>", "Search forward"],
        ["?<pattern>", "Search backward"],
        ["n / N", "Next / previous match"],
        [":s/old/new/g", "Replace all on line"],
        [":%s/old/new/g", "Replace all in file"],
        [":%s/old/new/gc", "Replace all (confirm each)"],
      ],
      "File Commands": [
        [":w", "Save file"],
        [":wq / ZZ", "Save and quit"],
        [":q!", "Quit without saving"],
        [":e <file>", "Open a file"],
        [":sp <file>", "Horizontal split"],
        [":vsp <file>", "Vertical split"],
        ["Ctrl+W hjkl", "Navigate splits"],
        [":tabnew", "Open new tab"],
        ["gt / gT", "Next / previous tab"],
      ],
      "Macros": [
        ["q<a>", "Start recording macro a"],
        ["q", "Stop recording macro"],
        ["@<a>", "Play macro a"],
        ["@@", "Replay last macro"],
        ["10@a", "Play macro a 10 times"],
      ],
    },
  },
};

export const SECTION_KEYS = Object.keys(DATA);
